### ISSUE TITLE
Terminliste: Anzeigefehler beim Abstand zwischen Event-Date-Kacheln 

### ISSUE THREAD

**Issue by csw-** [RRZE-Webteam/fau-events-veraltet-#16]
Im Firefox (getestet mit 38.7.0, 46.0.1) werden die Abstände zwischen den "Event-Date"-Kacheln nicht korrekt angezeigt (Abstand zu gering), wenn im Event kein Ort eingetragen worden ist.

**Siehe Bild:**
![termine-firefox](https://cloud.githubusercontent.com/assets/6545158/15142641/461493c2-16a6-11e6-8116-a846895c81b8.jpg)

**Korrekte Anzeige (z.B. Chrome)**
![termine-chrome](https://cloud.githubusercontent.com/assets/6545158/15142640/461237da-16a6-11e6-9912-687d13096eb1.jpg)

**Comment by xwolfde** [comment]
Ist Theme-Sache, nicht vom Plugin.

Ich hatte den Abstand gerade erst erhöht (vorher waren die Boxen aufeinander ohne Abstand, wenn die zweite Zeile fehlte) und finde den jetzt eigentlich so in Ordnung..
Der Abstand entspricht nun genau dem Line-Height der zweiten Zeile + einen Offset von glaub ich 5 px.

Klar können wir das wie vorgeschlagen erhöhen. Aber das hat dann den Nachteil, das bei vielen Termine in der List zu weit nach unten scrollen muss nur wegen dem erhöhten Whitespace.
Der obrige Abstand war so damals bei der FAU-Website abgenommen.

**Comment by csw-** [comment]
Ach so, das heißt es wird im Firefox eigentlich korrekt und in den anderen Browsern falsch?

**Comment by csw-** [comment]
@xwolfde @rvdforst 
Ich bin gerade auf einer unserer Einrichtungsseiten auf einen weiteren (neuen?) unschönen Bug gestoßen.
Hier kleben die Kacheln bei den Ganztägigen Terminen direkt aneinander: siehe Anhang

![termine_kacheln](https://cloud.githubusercontent.com/assets/6545158/18671076/eedde882-7f42-11e6-8d3b-1cdd67141de9.png)

**Comment by csw-** [comment]
@xwolfde Der hier kann wohl mit dem Wechsel auf das neue Kalender-Plugin geschlossen werden.
